// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"projecttest/internal/app/biz"
	"projecttest/internal/app/data"
	"projecttest/internal/app/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := data.NewDb()
	userRepo := data.NewUserRepo(db)
	userUsecase := biz.NewUserUsercase(userRepo)
	userService := service.NewUserService(userUsecase)
	app := NewApp(userService)
	return app
}
